<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="13" passed="9" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-12T16:51:05 EDT" name="Suite" finished-at="2022-08-12T16:51:30 EDT" duration-ms="24943">
    <groups>
    </groups>
    <test started-at="2022-08-12T16:51:05 EDT" name="Landing Page in Chrome" finished-at="2022-08-12T16:51:18 EDT" duration-ms="12411">
      <class name="com.qa.app.tests.LandingPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:05 EDT" name="setUp" finished-at="2022-08-12T16:51:14 EDT" duration-ms="8546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="landingPageSetUp()[pri:0, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:14 EDT" name="landingPageSetUp" finished-at="2022-08-12T16:51:14 EDT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- landingPageSetUp -->
        <test-method retried="true" signature="landingPageTittleTest()[pri:1, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:14 EDT" name="landingPageTittleTest" description="Varifying Landing Page Tittle" finished-at="2022-08-12T16:51:14 EDT" duration-ms="40" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.qa.app.tests.LandingPageTest.landingPageTittleTest(LandingPageTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- landingPageTittleTest -->
        <test-method retried="true" signature="landingPageTittleTest()[pri:1, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:14 EDT" name="landingPageTittleTest" description="Varifying Landing Page Tittle" finished-at="2022-08-12T16:51:14 EDT" duration-ms="8" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.qa.app.tests.LandingPageTest.landingPageTittleTest(LandingPageTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- landingPageTittleTest -->
        <test-method retried="true" signature="landingPageTittleTest()[pri:1, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:15 EDT" name="landingPageTittleTest" description="Varifying Landing Page Tittle" finished-at="2022-08-12T16:51:15 EDT" duration-ms="7" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.qa.app.tests.LandingPageTest.landingPageTittleTest(LandingPageTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- landingPageTittleTest -->
        <test-method signature="landingPageTittleTest()[pri:1, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:15 EDT" name="landingPageTittleTest" description="Varifying Landing Page Tittle" finished-at="2022-08-12T16:51:15 EDT" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy123] but found [Rahul Shetty Academy]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.qa.app.tests.LandingPageTest.landingPageTittleTest(LandingPageTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- landingPageTittleTest -->
        <test-method signature="verifyHeader()[pri:2, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:15 EDT" name="verifyHeader" description="Verifying the Header on Landing Page" finished-at="2022-08-12T16:51:15 EDT" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHeader -->
        <test-method signature="verifyLoginButton()[pri:3, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:15 EDT" name="verifyLoginButton" description="Verifying if Login Button is clickable or not" finished-at="2022-08-12T16:51:15 EDT" duration-ms="75" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginButton -->
        <test-method signature="verifyJoinbutton()[pri:4, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:15 EDT" name="verifyJoinbutton" description="Verifying is Join Button is clickable or not" finished-at="2022-08-12T16:51:16 EDT" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyJoinbutton -->
        <test-method signature="getLogin()[pri:5, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:16 EDT" name="getLogin" description="Clicking on Login Button and verifying that user is on Login Page" finished-at="2022-08-12T16:51:17 EDT" duration-ms="1600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.app.tests.LandingPageTest@e383572]" started-at="2022-08-12T16:51:17 EDT" name="tearDown" finished-at="2022-08-12T16:51:18 EDT" duration-ms="731" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.app.tests.LandingPageTest -->
    </test> <!-- Landing Page in Chrome -->
    <test started-at="2022-08-12T16:51:18 EDT" name="Tests in  Firefox" finished-at="2022-08-12T16:51:30 EDT" duration-ms="12019">
      <class name="com.qa.app.tests.LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:18 EDT" name="setUp" finished-at="2022-08-12T16:51:24 EDT" duration-ms="5454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="loginPageSetUp()[pri:0, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:24 EDT" name="loginPageSetUp" finished-at="2022-08-12T16:51:26 EDT" duration-ms="2482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageSetUp -->
        <test-method signature="verifyLoginPageHeader()[pri:1, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:26 EDT" name="verifyLoginPageHeader" description="Verifying the Header on Login Page" finished-at="2022-08-12T16:51:26 EDT" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageHeader -->
        <test-method signature="verifyRememberMeLink()[pri:2, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:26 EDT" name="verifyRememberMeLink" description="Verifying if Remember Me link is working or not on Login Page" finished-at="2022-08-12T16:51:26 EDT" duration-ms="57" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRememberMeLink -->
        <test-method signature="verifySignUp()[pri:3, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:26 EDT" name="verifySignUp" description="Verifying if Sign Up link is working or not on Login Page" finished-at="2022-08-12T16:51:27 EDT" duration-ms="57" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySignUp -->
        <test-method signature="verifyForgotPassword()[pri:4, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:27 EDT" name="verifyForgotPassword" description="Verifying if Forgot Password is working or not on Login Page" finished-at="2022-08-12T16:51:27 EDT" duration-ms="56" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyForgotPassword -->
        <test-method signature="doLogin()[pri:5, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:27 EDT" name="doLogin" description="Doing Login and verifying if user is Logged in or not and is on Home Page" finished-at="2022-08-12T16:51:30 EDT" duration-ms="3149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.app.tests.LoginPageTest@466276d8]" started-at="2022-08-12T16:51:30 EDT" name="tearDown" finished-at="2022-08-12T16:51:30 EDT" duration-ms="706" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.app.tests.LoginPageTest -->
    </test> <!-- Tests in  Firefox -->
  </suite> <!-- Suite -->
</testng-results>
